Repository marchhq/march, pull requests merged in 2024-10, with the labels that each got.

#210 refactor: block api
  apps/backend/src/services/lib/block.service.js
Labels: hacktoberfest-accepted

#215 refactor: space
  apps/backend/src/models/lib/space.model.js
  apps/backend/src/services/lib/space.service.js
Labels: hacktoberfest-accepted

#220 space
  apps/backend/src/services/lib/space.service.js
  apps/frontend/src/components/Sidebar.tsx
Labels: hacktoberfest-accepted

#242 feat: get labels by space
  apps/backend/src/controllers/lib/label.controller.js
  apps/backend/src/models/lib/item.model.js
  apps/backend/src/routers/lib/space.route.js
  apps/backend/src/services/lib/label.service.js
Labels: hacktoberfest-accepted, hacktobarfest

#219 polished today board
  apps/frontend/src/app/(app)/today/page.tsx
  apps/frontend/src/components/AddToSpace.tsx
  apps/frontend/src/components/DropDownItems.tsx
  apps/frontend/src/components/Today/TodayPage.tsx
  apps/frontend/src/components/TodayItems.tsx
  apps/frontend/src/components/TodayMeetings.tsx
  apps/frontend/src/components/atoms/ShowAgenda.tsx
  apps/frontend/src/hooks/useEvents.ts
  apps/frontend/src/hooks/useMeetings.ts
  apps/frontend/src/hooks/usePersistedState.ts
  apps/frontend/src/styles/main.css
Labels: hacktoberfest-accepted, hacktobarfest

#237 feat/enable-strike-through
  apps/frontend/src/styles/main.css
Labels: community, hacktoberfest-accepted, hacktobarfest

#222 Feat: reading list
  apps/frontend/src/app/(app)/space/reading-list/page.tsx
  apps/frontend/src/components/Reading/AddItemForm.tsx
  apps/frontend/src/components/Reading/ItemsList.tsx
  apps/frontend/src/components/Reading/ReadingListComponent.tsx
  apps/frontend/src/lib/@types/Items/Block.ts
  apps/frontend/src/lib/@types/Items/Reading.ts
  apps/frontend/src/lib/@types/Items/Space.ts
  apps/frontend/src/lib/store/reading.store.ts
Labels: hacktoberfest-accepted, hacktobarfest

#241 feat: profile ui
  apps/frontend/src/app/(app)/profile/page.tsx
  apps/frontend/src/components/profile/Integrations.tsx
  apps/frontend/src/components/profile/UserInfo.tsx
  apps/frontend/src/lib/icons/Calendar.tsx
  apps/frontend/src/lib/icons/Google.tsx
  apps/frontend/src/lib/store/user.store.ts
Labels: hacktobarfest

#270 fix: taskList styling on editor
  apps/frontend/src/app/layout.tsx
  apps/frontend/src/styles/main.css
  apps/frontend/src/styles/tiptap.css
Labels: need for alpha launch

#252 Feat: linear integration
  .github/ISSUE_TEMPLATE/linear-triage--feat error.md
  .github/ISSUE_TEMPLATE/linear-triage--ui.md
  .github/ISSUE_TEMPLATE/linear-triage-feat.md
  .github/ISSUE_TEMPLATE/linear-triage-ui error.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  apps/backend/.env.example
  apps/backend/src/controllers/integration/linear.controller.js
  apps/frontend/src/app/auth/linear/route.ts
  apps/frontend/src/components/profile/Integrations.tsx
  apps/frontend/src/hooks/useLinear.ts
  apps/frontend/src/lib/constants/cookie.ts
Labels: hacktoberfest-accepted, hacktobarfest, need for alpha launch

#255 feat: meetings
  apps/frontend/src/app/(app)/inbox/page.tsx
  apps/frontend/src/app/(app)/profile/page.tsx
  apps/frontend/src/app/(app)/space/meetings/[meetingId]/page.tsx
  apps/frontend/src/app/(app)/space/meetings/page.tsx
  apps/frontend/src/app/(app)/space/meetings/page2.tsx
  apps/frontend/src/app/(app)/space/notes/[noteId]/page.tsx
  apps/frontend/src/app/app/layout.tsx
  apps/frontend/src/components/DropDownItems.tsx
  apps/frontend/src/components/FeedbackModal/FeedbackModal.tsx
  apps/frontend/src/components/Inbox/InboxAddItem.tsx
  apps/frontend/src/components/Inbox/InboxExpandedItem.tsx
  apps/frontend/src/components/Inbox/InboxItems.tsx
  apps/frontend/src/components/Inbox/InboxPage.tsx
  apps/frontend/src/components/Inbox/InboxSection.tsx
  apps/frontend/src/components/Reading/AddItemForm.tsx
  apps/frontend/src/components/Reading/ItemsList.tsx
  apps/frontend/src/components/Reading/ReadingListComponent.tsx
  apps/frontend/src/components/Sidebar.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekPage.tsx
  apps/frontend/src/components/Today/TodayPage.tsx
  apps/frontend/src/components/TodayMeetings.tsx
  apps/frontend/src/components/atoms/DynamicDate.tsx
  apps/frontend/src/components/meetings/MeetNotes.tsx
  apps/frontend/src/components/meetings/MeetingsPage.tsx
  apps/frontend/src/components/meetings/Stack.tsx
  apps/frontend/src/components/profile/UserInfo.tsx
  apps/frontend/src/components/ui/calendar.tsx
  apps/frontend/src/components/ui/dropdown.tsx
  apps/frontend/src/lib/store/meets.store.ts
  apps/frontend/src/utils/meet.ts
Labels: need for alpha launch

#282 SAT - 186 : [ui] add loading screen with a message in on-boarding last step
  apps/frontend/src/app/(onboarding)/stack/page.tsx
  apps/frontend/src/contexts/AuthContext.tsx
  apps/frontend/src/lib/icons/Loader.tsx
  apps/frontend/tailwind.config.ts
Labels: hacktoberfest-accepted, hacktobarfest

#267 [wip] ui + feat/this-week
  apps/backend/src/models/lib/item.model.js
  apps/frontend/package.json
  apps/frontend/src/components/Inbox/InboxItems.tsx
  apps/frontend/src/components/ThisWeek/CustomKanban.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekArrows.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekExpandedItem.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekItem.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekNewItem.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekPage.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekSection.tsx
  apps/frontend/src/lib/@types/Items/Items.ts
  apps/frontend/src/lib/store/items.store.ts
  apps/frontend/src/utils/datetime.ts
  pnpm-lock.yaml
Labels: need for alpha launch

#314 updated stores for space and added cycle store
  apps/frontend/src/app/(app)/this-week/page.tsx
  apps/frontend/src/components/AddToSpace.tsx
  apps/frontend/src/components/DropDownItems.tsx
  apps/frontend/src/components/Inbox/InboxActions.tsx
  apps/frontend/src/components/Inbox/InboxAddItem.tsx
  apps/frontend/src/components/Inbox/InboxExpandedItem.tsx
  apps/frontend/src/components/Inbox/InboxItems.tsx
  apps/frontend/src/components/Inbox/InboxPage.tsx
  apps/frontend/src/components/Inbox/InboxSection.tsx
  apps/frontend/src/components/Sidebar.tsx
  apps/frontend/src/components/ThisWeek/CustomKanban.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekExpandedItem.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekPage.tsx
  apps/frontend/src/components/TodayItems.tsx
  apps/frontend/src/hooks/useEvents.ts
  apps/frontend/src/lib/@types/Items/Cycle.ts
  apps/frontend/src/lib/@types/Items/Inbox.ts
  apps/frontend/src/lib/@types/Items/Space.ts
  apps/frontend/src/lib/@types/Items/TodayItems.ts
  apps/frontend/src/lib/store/cycle.store.ts
  apps/frontend/src/lib/store/inbox.store.ts
  apps/frontend/src/utils/datetime.ts
Labels: need for alpha launch

#315 fix notes store w new backend changes
  apps/frontend/src/app/(app)/space/layout.tsx
  apps/frontend/src/app/(app)/space/notes/[noteId]/page.tsx
  apps/frontend/src/app/(app)/space/notes/page.tsx
  apps/frontend/src/app/(onboarding)/stack/pagetest.tsx
  apps/frontend/src/components/Inbox/InboxExpandedItem.tsx
  apps/frontend/src/lib/@types/Items/Note.ts
  apps/frontend/src/lib/store/notes.store.ts
  apps/frontend/src/styles/main.css
Labels: need for alpha launch

#304 this week expanded view
  apps/frontend/src/app/(app)/this-week/page.tsx
  apps/frontend/src/components/Inbox/InboxExpandedItem.tsx
  apps/frontend/src/components/Inbox/InboxItems.tsx
  apps/frontend/src/components/ThisWeek/CustomKanban.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekArrows.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekExpandedItem.tsx
  apps/frontend/src/components/ThisWeek/ThisWeekPage.tsx
  apps/frontend/src/styles/main.css
Labels: need for alpha launch

#350 fix: notes redirecting to login page
  apps/frontend/src/app/(app)/space/notes/[noteId]/page.tsx
  apps/frontend/src/app/(app)/space/notes/page.tsx
  apps/frontend/src/lib/server/actions/redirectNote.ts
Labels: ready to be merged

#387 fix: husky install command is deprecated issue
  apps/frontend/package.json
Labels: hacktoberfest-accepted, hacktobarfest

#318 Feedback changes
  apps/backend/src/services/lib/feedback.service.js
  apps/frontend/src/components/FeedbackModal/FeedbackModal.tsx
  apps/frontend/src/components/Sidebar.tsx
  apps/frontend/src/components/atoms/InfoBox.tsx
  apps/frontend/src/components/atoms/IntegrationList.tsx
  apps/frontend/src/components/atoms/Preference.tsx
  apps/frontend/src/components/ui/toast.tsx
  apps/frontend/src/hooks/useUserInfo.ts
Labels: community

#445 fix: caret behaviour on notes space
  apps/frontend/src/components/Notes/NotesPage.tsx
  apps/frontend/src/hooks/useEditor.hook.ts
Labels: rtbm
